# This is the configuration used to check the rubocop source code.

inherit_from:
  - https://raw.githubusercontent.com/serverscom/best-practices/rubocop-0.88/.rubocop.yml
  - .rubocop_todo.yml

inherit_mode:
  merge:
    - Exclude

require:
  - rubocop-performance

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
